import streamlit as st
import pandas as pd
import joblib
import os


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Student Placement Predictor",
    page_icon="🎓",
    layout="centered",
    initial_sidebar_state="expanded"
)


# ============================================================
# CUSTOM CSS
# ============================================================

st.markdown(
    """
    <style>

    /* Main background */
    .stApp {
        background: linear-gradient(
            135deg,
            #f5f7fa 0%,
            #e4ecf7 100%
        );
    }

    /* Main title */
    .main-title {
        text-align: center;
        font-size: 42px;
        font-weight: 800;
        margin-bottom: 5px;
    }

    .subtitle {
        text-align: center;
        font-size: 18px;
        margin-bottom: 25px;
    }

    /* Info card */
    .info-card {
        padding: 20px;
        border-radius: 15px;
        background: white;
        box-shadow: 0px 4px 15px rgba(0,0,0,0.08);
        margin-bottom: 20px;
    }

    /* Result card */
    .result-card {
        padding: 25px;
        border-radius: 18px;
        background: white;
        box-shadow: 0px 5px 20px rgba(0,0,0,0.10);
        text-align: center;
        margin-top: 20px;
    }

    /* Footer */
    .footer {
        text-align: center;
        margin-top: 40px;
        padding: 20px;
        font-size: 14px;
    }

    </style>
    """,
    unsafe_allow_html=True
)


# ============================================================
# LOAD MODEL
# ============================================================

MODEL_PATH = "placement_model.pkl"


if not os.path.exists(MODEL_PATH):

    st.error(
        "❌ Model file not found!"
    )

    st.info(
        "Please make sure that 'placement_model.pkl' "
        "is in the same folder as 'app.py'."
    )

    st.stop()


try:

    model = joblib.load(MODEL_PATH)

except Exception as e:

    st.error(
        "❌ Unable to load the trained model."
    )

    st.code(str(e))

    st.stop()


# ============================================================
# HEADER
# ============================================================

st.markdown(
    '<div class="main-title">🎓 Student Placement Predictor</div>',
    unsafe_allow_html=True
)

st.markdown(
    """
    <div class="subtitle">
        Machine Learning based Student Placement Prediction System
    </div>
    """,
    unsafe_allow_html=True
)


st.divider()


# ============================================================
# PROJECT INTRODUCTION
# ============================================================

st.markdown(
    """
    <div class="info-card">

    <h3>📌 About This Application</h3>

    <p>
    This application uses a trained
    <b>Logistic Regression Machine Learning model</b>
    to predict whether a student is likely to be placed
    based on academic and study-related information.
    </p>

    </div>
    """,
    unsafe_allow_html=True
)


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.header("🎓 Student Placement")

    st.write(
        "Enter the student's information "
        "to generate a prediction."
    )

    st.divider()

    st.subheader("🤖 Model Information")

    st.write("**Algorithm:** Logistic Regression")

    st.write("**Test Accuracy:** 90.65%")

    st.write("**Cross Validation:** 90.76%")

    st.write("**ROC-AUC:** 0.9385")

    st.divider()

    st.caption(
        "This prediction is generated by a "
        "Machine Learning model and should be "
        "used for educational/analytical purposes."
    )


# ============================================================
# INPUT SECTION
# ============================================================

st.header("📊 Enter Student Information")

st.write(
    "Provide the following information about the student."
)


# ============================================================
# STUDY HOURS
# ============================================================

study_hours = st.number_input(
    "📚 Study Hours per Day",
    min_value=0.0,
    max_value=24.0,
    value=8.0,
    step=0.5,
    help="Average number of hours the student studies per day."
)


# ============================================================
# ATTENDANCE
# ============================================================

attendance = st.number_input(
    "📅 Attendance (%)",
    min_value=0.0,
    max_value=100.0,
    value=85.0,
    step=1.0,
    help="Student's attendance percentage."
)


# ============================================================
# SLEEP HOURS
# ============================================================

sleep_hours = st.number_input(
    "😴 Sleep Hours per Day",
    min_value=0.0,
    max_value=24.0,
    value=7.0,
    step=0.5,
    help="Average number of hours the student sleeps per day."
)


# ============================================================
# INTERNET USAGE
# ============================================================

internet_usage = st.number_input(
    "🌐 Internet Usage (Hours per Day)",
    min_value=0.0,
    max_value=24.0,
    value=4.0,
    step=0.5,
    help="Average daily internet usage."
)


# ============================================================
# ASSIGNMENTS
# ============================================================

assignments_completed = st.number_input(
    "📝 Assignments Completed",
    min_value=0,
    max_value=100,
    value=15,
    step=1,
    help="Number of assignments completed by the student."
)


# ============================================================
# PREVIOUS SCORE
# ============================================================

previous_score = st.number_input(
    "🎯 Previous Score",
    min_value=0.0,
    max_value=100.0,
    value=80.0,
    step=1.0,
    help="Previous academic score."
)


st.divider()


# ============================================================
# PREDICTION BUTTON
# ============================================================

predict_button = st.button(
    "🔮 Predict Placement",
    use_container_width=True
)


# ============================================================
# PREDICTION
# ============================================================

if predict_button:

    # --------------------------------------------------------
    # Create DataFrame
    # --------------------------------------------------------

    new_student = pd.DataFrame(
        [{
            "study_hours": study_hours,
            "attendance": attendance,
            "sleep_hours": sleep_hours,
            "internet_usage": internet_usage,
            "assignments_completed": assignments_completed,
            "previous_score": previous_score
        }]
    )


    # --------------------------------------------------------
    # Model Prediction
    # --------------------------------------------------------

    try:

        prediction = model.predict(new_student)[0]

        probability = model.predict_proba(
            new_student
        )[0][1]

    except Exception as e:

        st.error(
            "❌ Prediction failed."
        )

        st.code(str(e))

        st.stop()


    # --------------------------------------------------------
    # Result Section
    # --------------------------------------------------------

    st.header("📌 Prediction Result")


    if prediction == 1:

        st.success(
            "🎉 Student is predicted to be PLACED!"
        )

        result_text = "PLACED"

    else:

        st.error(
            "⚠️ Student is predicted to be NOT PLACED!"
        )

        result_text = "NOT PLACED"


    # --------------------------------------------------------
    # Probability
    # --------------------------------------------------------

    st.metric(
        label="📈 Placement Probability",
        value=f"{probability * 100:.2f}%"
    )


    st.progress(
        float(probability)
    )


    # --------------------------------------------------------
    # Probability Interpretation
    # --------------------------------------------------------

    if probability >= 0.75:

        st.info(
            "🟢 The model shows a high estimated "
            "probability of placement."
        )

    elif probability >= 0.50:

        st.warning(
            "🟡 The model shows a moderate estimated "
            "probability of placement."
        )

    else:

        st.warning(
            "🔴 The model shows a low estimated "
            "probability of placement."
        )


    # ========================================================
    # STUDENT DATA SUMMARY
    # ========================================================

    st.subheader("📋 Student Information Summary")

    summary_df = pd.DataFrame(
        {
            "Feature": [
                "Study Hours",
                "Attendance",
                "Sleep Hours",
                "Internet Usage",
                "Assignments Completed",
                "Previous Score"
            ],

            "Value": [
                study_hours,
                f"{attendance}%",
                sleep_hours,
                internet_usage,
                assignments_completed,
                previous_score
            ]
        }
    )


    st.dataframe(
        summary_df,
        use_container_width=True,
        hide_index=True
    )


    # ========================================================
    # TECHNICAL RESULT
    # ========================================================

    with st.expander("🔍 View Technical Prediction Data"):

        st.write("Prediction value:")

        st.code(str(prediction))

        st.write("Predicted class:")

        st.code(result_text)

        st.write("Model probability:")

        st.code(f"{probability:.6f}")


# ============================================================
# FOOTER
# ============================================================

st.divider()

st.markdown(
    """
    <div class="footer">

    <b>🎓 Student Placement Prediction System</b>

    <br><br>

    Built with Python, Pandas, Scikit-learn & Streamlit

    <br>

    Machine Learning Project

    </div>
    """,
    unsafe_allow_html=True
)